modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Anvil%20Restoration"
logoFile="icon.png"

[[mods]]
modId="anvilrestoration"
version="2.0"
displayName="Anvil Restoration"
displayURL="https://curseforge.com/minecraft/mc-mods/anvil-restoration"
authors="Rick South"
description='''Adds the ability to repair placed anvils with iron ingots and destroy them with obsidian.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.anvilrestoration]]
    modId="collective"
    mandatory=true
    versionRange="[6.22,)"
    ordering="NONE"
    side="BOTH"