modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Anvil%20Restoration"
logoFile="icon.png"

[[mods]]
modId="anvilrestoration"
version="2.3"
displayName="Anvil Restoration"
displayURL="https://serilum.com/mod/anvil-restoration"
authors="Rick South"
description='''Adds the ability to repair placed anvils with iron ingots and destroy them with obsidian.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.anvilrestoration]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.anvilrestoration]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "anvilrestoration.mixins.json"